name: AI Agent

on:
  workflow_dispatch:
    inputs:
      provider:
        description: 'AI provider ID'
        required: false
        default: 'gemini'
        type: string
      prompt:
        description: 'Instruction for the AI Agent'
        required: true
        type: string
      model:
        description: 'Gemini Model ID'
        required: false
        default: 'gemini-2.5-flash'
  schedule:
    # Run every Monday and Thursday at 00:00 UTC
    - cron: '0 0 * * 1,4'

jobs:
  execute-agent:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Execute AI Task
        if: github.event_name != 'schedule'
        uses: mz-codes/mz-ai-agent-action@v1
        with:
          provider: ${{ inputs.provider }}
          prompt: ${{ inputs.prompt }}
          model: ${{ inputs.model }}
          credentials-map: ${{ secrets.AI_AGENT_CREDENTIALS }}
          location: global
          artifact-name: agent-result-log
          retention-days: 1
